#!/bin/bash
#Meu Primeiro Script

#Listando os Diretorios do Linux
ls -lha /
read
clear

#Atualizando o Apt ou Apt-Get
apt update
echo "Listas Atualizadas!!!"
read
cls

#Desligando O servidor 
shutdown -h now 
